### ISSUE TITLE
Example for first introduction

### ISSUE THREAD

**Issue by mitchelloharawild** [numbats/gganimate-workshop#4]
The introductory vignette to gganimate features animations using the iris data in various ways.
I think something similar (but perhaps more interesting) would be a useful first look at animating a ggplot.

**Comment by mitchelloharawild** [comment]
https://cran.r-project.org/web/packages/gganimate/vignettes/gganimate.html

**Comment by uschiLaa** [comment]
How about doing the datasaurus_dozen?

**Comment by mitchelloharawild** [comment]
Sounds good :+1:
